project:
  type: website
  output-dir: docs

website:
  title: "Hanna Venera"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers/index.qmd
        text: Papers
      - href: awards/index.qmd
        text: Awards
      - href: media/index.qmd
        text: Media
  
body-footer:
    left: "Copyright 2025, Hanna Venera"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

